# Generated by Django 3.2.12 on 2022-02-12 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curl', models.CharField(max_length=64, unique=True)),
                ('passwd', models.CharField(max_length=64)),
                ('ipaddr', models.CharField(max_length=16)),
                ('port', models.PositiveIntegerField()),
                ('datetime_reg', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('puuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('repoeter', models.CharField(max_length=64)),
                ('datetime_rev', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
