# Generated by Django 3.2.12 on 2022-02-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_repoeter_poster_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='content',
        ),
    ]
