# Generated by Django 3.2.12 on 2022-02-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_poster_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
